import Head from "next/head";
import Footer from "../components/footer/Footer";
import Header from "../components/header/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Rahgozar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/gh/rastikerdar/vazirmatn@v33.003/Vazirmatn-font-face.css"
          as="font"
          type="font/woff"
        />
      </Head>
      <div>
        <Header />
        <Footer />
      </div>
    </div>
  );
}
