import Grid2 from "@mui/material/Unstable_Grid2/Grid2";
import Head from "next/head";
import MainLayout from "../components/layouts/MainLayout";
import TextContainer from "../components/sideBar/textContainer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Rahgozar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid2>
        <MainLayout>
          <TextContainer />
        </MainLayout>
      </Grid2>
    </div>
  );
}
